definitions:
  buildTestStep: &buildTestStep
    name: Run tests
    image:
      name: fontoxmltoolsinternal.azurecr.io/build-tools/fontoxml-pipeline-test-build:latest
      username: $TOOLS_INTERNAL_REGISTRY_USERNAME
      password: $TOOLS_INTERNAL_REGISTRY_PASSWORD
    script:
      - run-unit-tests

  buildSyncStep: &buildSyncStep
    name: Push to Github
    image:
      name: fontoxmltoolsinternal.azurecr.io/build-tools/fontoxml-pipeline-push-to-github:test
      username: $TOOLS_INTERNAL_REGISTRY_USERNAME
      password: $TOOLS_INTERNAL_REGISTRY_PASSWORD
    script:
      - push-to-github

pipelines:
  default:
    - step: *buildTestStep
    - step: *buildSyncStep

  tags:
    "**":
      - step: *buildTestStep
      - step: *buildSyncStep
